# .streamlit/secrets.toml
#server = "DESKTOP-GL2TFSM\\MSSQLSERVER02" 
#database = "propertyDatabase"
#username = "sa"
#password = "Myp@ssword"

server = "PropertyDatabase.mssql.somee.com"
database = "propertyDatabase"
username = "prashantgole_SQLLogin_1"
password = "rai1zfqvlc"